id: P007992
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19901
  title: མཉེན་ཆས་མ་ལག་རྩིས་འཕྲུལ་ཁོག་ཏུ་འཇོག་ལུགས་དང་པོའི་ལས་ཅན་འཇུག་པའི་སྒོ།
  author: ''
  volumes:
    4eef41d2aa694db696b46f92f7cb8502:
      image_group_id: I2PD20730
      title: ''
      volume_number: 1
      total_pages: 44
ebook_metadata:
  title: མཉེན་ཆས་མ་ལག་རྩིས་འཕྲུལ་ཁོག་ཏུ་འཇོག་ལུགས་དང་པོའི་ལས་ཅན་འཇུག་པའི་སྒོ།
  author: ''
  sku: P007992
  cover: cover.jpg
  layers:
  - pagination
