id: P007992
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:53:49.434855
source_metadata:
  id: bdr:W2PD19901
  title: མཉེན་ཆས་མ་ལག་རྩིས་འཕྲུལ་ཁོག་ཏུ་འཇོག་ལུགས་དང་པོའི་ལས་ཅན་འཇུག་པའི་སྒོ།
  author: ''
  volumes:
    c9b72ae1720947d09eb593fe5bad5145:
      image_group_id: I2PD20730
      title: Volume 1 of mnyen chas ma lag rtsis 'phrul khog tu 'jog lugs dang po'i
        las can 'jug pa'i sgo/
      volume_number: 1
      total_pages: 44
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
