id: opecha:P007992
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19901
  title: མཉེན་ཆས་མ་ལག་རྩིས་འཕྲུལ་ཁོག་ཏུ་འཇོག་ལུགས་དང་པོའི་ལས་ཅན་འཇུག་པའི་སྒོ།
  volume:
    c9b72ae1720947d09eb593fe5bad5145:
      image_group_id: I2PD20730
      title: Volume 1 of mnyen chas ma lag rtsis 'phrul khog tu 'jog lugs dang po'i
        las can 'jug pa'i sgo/
      volume_number: 1
      total_pages: 44
  author: ''
ebook_metadata:
  title: མཉེན་ཆས་མ་ལག་རྩིས་འཕྲུལ་ཁོག་ཏུ་འཇོག་ལུགས་དང་པོའི་ལས་ཅན་འཇུག་པའི་སྒོ།
  author: ''
  sku: P007992
  cover: cover.jpg
  layers:
  - pagination
